### ISSUE TITLE
RollDice fix

### ISSUE THREAD

**Issue by michelebanfi** [marco97pa/worldadventure#1]
In [game.js](https://github.com/marco97pa/worldadventure/blob/master/game.js) quando viene fatto il random per il dato, è sbagliato il valore di massimo.
`steps = Math.floor(Math.random() * 6) + 1;` 
Non mi sembrava il caso di fare una pr.

**Comment by marco97pa** [comment]
@michelebanfi 
Grazie, ogni contributo è ben accetto. Non mi ero mai accorto dell'errore. Risolverò il bug tra pochissimo.
